spring:
  application:
    name: ChatService

  datasource:
    url: jdbc:postgresql://localhost:5432/chat_service_db
    username: siri_hate
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  aop:
    proxy-target-class: false

server:
  address: localhost
  port: 8084
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: admin200
    keyStoreType: PKCS12
    keyAlias: starthub

logging:
  level:
    root: INFO
    org.springframework.web.socket: DEBUG
    org.springframework.web.socket.client: DEBUG
    org.springframework.web.socket.messaging: DEBUG
    org.springframework.messaging.simp: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true